### PR TITLE
Error logging and structure changes

### PR DESCRIPTION
**Pull request by khatkar**
- Moved case class/objects to separate files. This improves clarity and structure.
- Fixed the use of `null` in comparison expressions. The solution was to wrap the `null` in
  an `Option` and then checking if the object `isDefined`.
- Implemented logging with typesafe/scalalogging library
- Upped scala-async version to 0.9.5
- Heavy code style changes. Please see [https://github.com/databricks/scala-style-guide]

### CODE REVIEW

**Comment by Kai-Chen** [comment]
@khatkar Thank you for the submission.

While I'm usually unusually agnostic to coding styles, in this particular situation I'm not particularly attracted to merging this. This style is Java, not Scala.  And there is an official Scala style guide, which I'm certain that will not be pleasing to everybody.  So I lean towards to keeping to whatever the original style it was written in, because no other standard is better to go by.  So you write like scalaz if you are submitting to scalaz, and you write like jdk if you submit to jdk.  You never write like jdk when you submit to scalaz.

However, since Eve is the one who started the project, I will defer to her.

@freeeve Please comment.  Thanks!

**Comment by khatkar** [comment]
@Kai-Chen Thank you for reviewing. My changes follow the DataBricks' Scala style guide and I believe many other programmers are following it. Quoting from them, 

> With over 800 contributors, Spark is to the best of our knowledge the largest open-source project in Big Data and the most active project written in Scala. This guide draws from our experience coaching and working with engineers contributing to Spark as well as our Databricks engineering team.

To me it makes sense to follow their guide as it overlaps with Scala's official style guide and the fact that so many programmers are contributing to it, people are inclined to follow. I care less if it is Java style or Scala, but the style is adopted for enhanced clarity. The code is written once but read multiple times. Many lines are way over a good limit of 100 characters (this primarily includes defining all parameters in one line, which is not recommended). On any open source project like this, it always helps that people are familiar with the style rules. If there is any style that this project is following, please let the users know so that contributions to style changes do not happen.

PS: The absence of scaladoc makes it less likely for people to contribute.

**Comment by Kai-Chen** [comment]
@khatkar I understand all your logic.  Spark, though, is trying to cater to Java programmers; they've even switched to maven as the official build.  They also have 500+ contributors, which I doubt we'd get here :)  A team of that size would definitely need a style guide.

My point here is centered around pragmatism.  Deciding which style is best almost always ends up like a theological debate.  And since the code --not the style -- is the essence, my personal rule as outlined above applies here.  As long as the code is not very obfuscated, there will be no style changes until it becomes necessary.  Otherwise what you've gained is not worth the time, because there's always somebody out there that will definitely be not happy with your changes :)

Let's wait to hear what Eve has to say.

Best regards,
p.s. I hope you still have the transaction related code somewhere.  Since you've got the stylized commit already, getting a patch should be easy :) I'd love to take a look at that.  Thanks!

**Comment by khatkar** [comment]
@Kai-Chen We (RiskSense, Inc.) are using the transactions already. You can take a look at [https://github.com/risksense/AnormCypher]

**Comment by Kai-Chen** [comment]
@khatkar Thanks!

I'm understanding that your CypherBatch is a sequence of individual Transactions, not a transaction including a group of statements, is that right?  Are you working on executing code in open transactions?

**Comment by khatkar** [comment]
@Kai-Chen Yes, CypherBatch is a set of Transactions and the transactions are executed on an open connection. The method `sendTransaction` in Neo4jREST.scala returns the commit endpoint at which the future requests are made.

**Comment by Kai-Chen** [comment]
@khatkar OK.  Most of the it is pretty good and is similar to what I have in my WIP.  The only thing that's missing is that, sometimes the statements in a single transaction can depend on the results of a previous statement in the same transaction.  It's hard to express that in a `Seq[CypherStatement]`.  That's why I provide a code block call back to the `withTx()` method.  One thing I'm concerned with that approach is that the user may inadvertently use Future in the block, but the block is really meant to be executed in sequence, not concurrently.  So that's an issue that I've been thinking about.

I don't know what I can pick from your repo, though.  A draft version should be done by next week, and if you don't mind taking a look at that and trying it out with your apps, I'd really appreciate that.

Thanks again!

**Comment by khatkar** [comment]
@Kai-Chen Sure. I didn't made a PR with this transactions feature because I knew about the issue you mentioned. It was urgent for me to use trancactions so I wrote some bare minimum part to go through. Let me know when you finish and I would be happy to test.

**Comment by Kai-Chen** [comment]
@khatkar I will hurry up then :)

**Comment by Kai-Chen** [comment]
@khatkar The commit [9a7e7fc23](https://github.com/AnormCypher/AnormCypher/commit/9a7e7fc23d084cbca0daa248e7867bba5967d6d0) in the 0.9 branch should be decent enough now for testing.  Sorry I don't have the doc written up yet.  But there are tests, which shows (I hope) clearly how the API works.

One important thing to remember when passing code to `withTx` is that all the statements in the block should execute sequentially.  In other words, the code shouldn't return a Future.  The best way to do this is to make sure each CypherStatement is applied as in `Cypher(...)()` before moving on to the next.  I haven't figured out how to make the compiler check this without digging into macro, which might be an overkill at this time.

Let me know if you find any bugs.  Thanks!  I will make an announcement on the mailing list soon also, after I finish up the documentation.

**Comment by Kai-Chen** [comment]
The 0.9 branch has just been merged in master and released.

**Comment by khatkar** [comment]
@Kai-Chen I had a chance to read/test your code last week, looks good. Thank you :)

**Pull request closed without merging**
